# Generated by Django 5.1 on 2024-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
